recipe_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('recipe_store.urls')),
]

recipe_store/urls.py
# recipe_store/urls.py

from django.urls import path
from .views import (
    RecipeListView, 
    RecipeDetailView, 
    #RecipeUpdateView,
    recipe_edit, 
    RecipeDeleteView, 
    RecipeCreateView,
    IngredientListView,
    IngredientCreateView,
    IngredientDetailView,
    IngredientUpdateView,
    IngredientDeleteView,
    PantryListView,
    RecipeIngredientAdd,
)

urlpatterns = [
    path('', RecipeListView.as_view(), name='home'),
    path('recipe/new', RecipeCreateView.as_view(), name='recipe_new'),
    path('recipe/<int:pk>/', RecipeDetailView.as_view(), name='recipe_detail'),
    path('recipe/<int:pk>/edit/', recipe_edit, name='recipe_edit'),
    path('recipe/<int:pk>/edit/add_ingredient', RecipeIngredientAdd.as_view(), name='recipe_ing_add'),
    #path('recipe/<int:pk>/edit/', RecipeUpdateView.as_view(), name='recipe_edit'),
    path('recipe/<int:pk>/delete/', RecipeDeleteView.as_view(), name='recipe_delete'),
    path('ingredients', IngredientListView.as_view(), name='ingredients'),
    path('ingredients/new', IngredientCreateView.as_view(), name='ingredient_new'),
    path('ingredients/<int:pk>/', IngredientDetailView.as_view(), name='ingredient_detail'),
    path('ingredients/<int:pk>/edit/', IngredientUpdateView.as_view(), name='ingredient_edit'),
    path('ingredients/<int:pk>/delete/', IngredientDeleteView.as_view(), name='ingredient_delete'),
    path('pantry', PantryListView.as_view(), name='pantry'),
]

recipe_store/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
class Unit(models.Model):
    
    # Not sure if I care about what type of measure this is
    #VOLUME = 'VOLUME'
    #MASS = 'MASS'

    #MEASURE_CHOICES = [
    #    (VOLUME, 'Volume'),
    #    (MASS, 'Mass'),
    #]

    name = models.CharField(max_length = 20)
    abbreviation = models.CharField(max_length = 5)
    #measure = models.CharField(max_length = 20, choices = MEASURE_CHOICES, default = VOLUME)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        pass
        #TO-DO
        #return reverse('')

class Ingredient(models.Model):
    
    name = models.CharField(max_length = 40)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('ingredient_detail', args=[str(self.id)])  

class PantryItem(models.Model):

    item = models.ForeignKey(Ingredient, on_delete=models.CASCADE)
    quantity = models.DecimalField(decimal_places=2, max_digits=4)
    units = models.ForeignKey(Unit, on_delete=models.CASCADE)

    def __str__(self):
        return self.item.name

    def get_absolute_url(self):
        pass
        #TO-DO
        #return reverse('')

class Recipe(models.Model):
    
    ITALIAN = 'IT'
    ASIAN = 'AS'
    AMERICAN = 'AM'

    TYPE_CHOICES = [
        (ITALIAN, 'Italian'),
        (ASIAN, 'Asian'),
        (AMERICAN, 'American')
    ]
    
    name = models.CharField(max_length = 100)
    type = models.CharField(max_length = 20, choices = TYPE_CHOICES, default = AMERICAN)
    servings = models.IntegerField()
    prep_time = models.DecimalField(decimal_places=2, max_digits=5) # TODO - change this to an int to hold minutes
    cook_time = models.DecimalField(decimal_places=2, max_digits=5) # TODO - change this to an int to hold minutes
    ingredients = models.ManyToManyField(Ingredient, through='RecipeIngredient')
    directions = models.TextField()

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('recipe_detail', args=[str(self.id)])

class RecipeIngredient(models.Model):
    
    recipe = models.ForeignKey(Recipe, on_delete = models.CASCADE)
    ingredient = models.ForeignKey(Ingredient, on_delete = models.CASCADE)
    quantity = models.DecimalField(decimal_places=2, max_digits=4)
    units = models.ForeignKey(Unit, on_delete=models.CASCADE)
    style = models.TextField(default="", blank=True)

    def __str__(self):
        return self.recipe.name + ": " + self.ingredient.name

    def get_absolute_url(self):
        pass
        # TODO
        #return reverse('')

recipe_store/forms.py
from django import forms
from recipe_store.models import Recipe, RecipeIngredient

class RecipeForm(forms.ModelForm):
    class Meta:
        model = Recipe
        #fields = '__all__'
        exclude = ('ingredients',)
    
class RecipeIngredientForm(forms.ModelForm):
    class Meta:
        model = RecipeIngredient
        #fields = '__all__'
        exclude = ('recipe',)

recipe_store/views.py
from recipe_store.models import Recipe, RecipeIngredient
from recipe_store.forms import RecipeForm, RecipeIngredientForm
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404

from .models import Recipe, RecipeIngredient, Ingredient, PantryItem


# Create your views here.
class RecipeListView(ListView):
    model = Recipe
    template_name = 'home.html'
    context_object_name = 'recipes'

class RecipeDetailView(DetailView):
    model = Recipe
    template_name = 'recipe_detail.html'

# TODO - consider changing this to a function based view
class RecipeCreateView(CreateView):
    model = Recipe
    template_name = 'recipe_new.html'
    #need to add Ingredients to fields once I understand how the selection should work
    fields = ['name', 'type', 'servings', 'prep_time', 'cook_time', 'directions']

# Attempt at a function based view for editing recipes, this can be modified into a funciton that handles both adding new recipes and editing existing recipes in the future.
def recipe_edit(request, pk):
    recipe = get_object_or_404(Recipe, pk=pk)
    ingredients = RecipeIngredient.objects.all().filter(recipe_id=pk)
    if request.method == "POST":
        r_form = RecipeForm(request.POST, instance=recipe)
        ri_forms = [RecipeIngredientForm(request.POST, prefix=str(x), instance=ingredients[x]) for x in range(len(ingredients))]

        if r_form.is_valid() and all([ri_form.is_valid() for ri_form in ri_forms]):
            #recipe = r_form.save(commit=False)
            recipe = r_form.save()
            
            # TODO - WORK ON RECIPEINGREDIENT PROCESSING
            for ri_form in ri_forms:
                ri_form.save()

            return HttpResponseRedirect(recipe.get_absolute_url())#, pk=recipe.pk)

           
    else:
        r_form = RecipeForm(instance=recipe)
        ri_forms = [RecipeIngredientForm(prefix=str(x), instance=ingredients[x]) for x in range(len(ingredients))]
    # DEBUG
    #import pdb; pdb.set_trace()
    return render(request, 'recipe_edit.html', {'recipe_form': r_form, 'recipeingredient_forms': ri_forms})

# Trying out a function based view to handle recipe updates
# class RecipeUpdateView(UpdateView):
#     model = Recipe
#     template_name = 'recipe_edit.html'
#     #need to add Ingredients to fields once I understand how the selection should work
#     fields = ['name', 'type', 'servings', 'prep_time', 'cook_time', 'directions']

class RecipeDeleteView(DeleteView):
    model = Recipe
    template_name = 'recipe_delete.html'
    success_url = reverse_lazy('home')

class IngredientListView(ListView):
    model = Ingredient
    template_name = 'ingredients.html'
    context_object_name = 'ingredients'

class IngredientCreateView(CreateView):
    model = Ingredient
    template_name = "ingredient_new.html"
    fields = ['name',]

class IngredientDetailView(DetailView):
    model = Ingredient
    template_name = "ingredient_detail.html"

class IngredientUpdateView(UpdateView):
    model = Ingredient
    template_name = 'ingredient_edit.html'
    fields = ['name',]

class IngredientDeleteView(DeleteView):
    model = Ingredient
    template_name = 'ingredient_delete.html'
    success_url = reverse_lazy('ingredients')

class PantryListView(ListView):
    model = PantryItem
    template_name = 'pantry.html'
    fields = ['item', 'quantity', 'units',]
    context_object_name = 'pantry_items'

class RecipeIngredientAdd(CreateView):
    model = RecipeIngredient
    template_name = 'recipe_ing_add.html'
    fields = ['ingredient', 'quantity', 'units', 'style',]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html>
    <head>
        <title>Recipe Box</title>
        <link href="{% static 'recipe_store/css/base.css' %}" rel="stylesheet">
    </head>
    <body>
        <header>
            <nav>
                <h1><a href="{% url 'home' %}" style="text-decoration: none;">Recipe Box</a></h1>
            </nav> 
        </header>
        {% block content %}
        {% endblock content %}
        <footer></footer>
    </body>
</html>

templates/home.html
<!-- templates/home.html -->

{% extends 'base.html' %}

{% block content %}
    <div class="submenu">
        <a href="{% url 'recipe_new' %}">New Recipe</a>
        <span> // </span>
        <a href="{% url 'ingredients' %}">Ingredients</a>
        <span> // </span>
        <!--TODO-->
        <a href="{% url 'pantry' %}">Pantry</a>
    </div>   
    <main>
        <ul>
            {% for recipe in recipes %}
                <li><a href="{% url 'recipe_detail' recipe.id %}">{{ recipe.name }}</a></li>
            {% empty %}
                <li>No recipes yet.</li>
            {% endfor %}
        </ul>
    </main> 
{% endblock content %}

templates/ingredient_delete.html
{% extends 'base.html' %}

{% block content %}
    <main>
        <h3>Delete Ingredient</h3>
        <form action="" method="post">{% csrf_token %}
            <p>Are you sure you want to delete "{{ ingredient.name }}"?</p>
            <input type="submit" value="Confirm">
        </form>
    </main>

{% endblock content %}

templates/ingredient_detail.html
{% extends 'base.html' %}

{% block content %}
    <div class="submenu">
        <a href="{% url 'ingredient_edit' ingredient.id %}">Edit Ingredient</a>
        <a href="{% url 'ingredient_delete' ingredient.id %}">Delete Ingredient</a>
    </div>   
    <main>
        <h2>{{ ingredient.name }}</h2>
    </main> 
{% endblock content %}

templates/ingredient_edit.html
{% extends 'base.html' %}

{% block content %}
    <main>
        <h3>Edit Ingredients</h3>
        <form action="" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            
            <input type="submit" value="Update">
        </form>
    </main>

{% endblock content %}

templates/ingredient_new.html
{% extends 'base.html' %}

{% block content %}
<main>
    <h3>New Ingredient</h3>
    <form action="" method="post">{% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Save">
    </form>
</main>
{% endblock content %}

templates/ingredients.html
{% extends 'base.html' %}

{% block content %}
    <div class="submenu">
        <a href="{% url 'ingredient_new' %}">New Ingredient</a>
    </div>   
    <main>
        <ul>
            {% for ingredient in ingredients %}
                <li><a href="{% url 'ingredient_detail' ingredient.id %}">{{ ingredient.name }}</a></li>
            {% empty %}
                <li>No recipes yet.</li>
            {% endfor %}
        </ul>
    </main> 
{% endblock content %}

templates/pantry.html
{% extends 'base.html' %}

{% block content %}
    <div class="submenu">
        <a href="{% url 'recipe_new' %}">New Recipe</a>
        <span> // </span>
        <a href="{% url 'ingredients' %}">Ingredients</a>
        <span> // </span>
    </div>   
    <main>
        <table>
            <tr>
                <th>Ingredient</th>
                <th>Qty</th>
                <th>Measure</th>
            </tr>
            {% for item in pantry_items %}
                <tr>
                    <td>{{ item.item }}</td>
                    <td>{{ item.quantity }}</td>
                    <td>{{ item.units }}</td>
                </tr>
            {% empty %}
                <tr>
                    <td colspan="3">Empty Pantry!</td>
                </tr>
            {% endfor %}
        </table>
    </main> 
{% endblock content %}

templates/recipe_delete.html
<!-- templates/recipe_delete.html -->

{% extends 'base.html' %}

{% block content %}
    <main>
        <h3>Delete Recipe</h3>
        <form action="" method="post">{% csrf_token %}
            <p>Are you sure you want to delete "{{ recipe.name }}"?</p>
            <input type="submit" value="Confirm">
        </form>
    </main>

{% endblock content %}

templates/recipe_detail.html
<!-- tempaltes/recipe_detail.html -->

{% extends 'base.html' %}

{%block content %}
    <div class="submenu">
        <a href="{% url 'recipe_new' %}">New Recipe</a>
        <a href="{% url 'recipe_edit' recipe.id %}">Edit Recipe</a>
        <a href="{% url 'recipe_delete' recipe.id %}">Delete Recipe</a>
    </div>
    <main>
        <div class="recipe-detail">
            <h2>{{ recipe.name }}</h2>
            <p>Type: {{ recipe.type }}</p>
            <p>Prep Time: {{ recipe.prep_time }}</p>
            <p>Cook Time: {{ recipe.cook_time }}</p>            
            <p>Servings: <span id="servings">{{ recipe.servings }}</span>  |  
                <label for="multiplier">Multiplier: </label>
                <select name="mulitplier" id="multiplier">
                    <option value="1" selected="selected">1</option>
                    <option value="2">2</option>
                    <option value="3">3</option>
                    <option value="4">4</option>
                    <option value="5">5</option>
                </select>
            </p>
            <h3>Ingredients</h3>
            <ul>
                {% for recipeingredient in recipe.recipeingredient_set.all %}
                    <li>{% if recipeingredient.quantity != 0 %}<span class="ing_qty">{{ recipeingredient.quantity }}</span> {{ recipeingredient.units }}
                        {% endif %}
                        {{ recipeingredient.ingredient }}
                        {% if recipeingredient.style == "" %}
                            </li>
                        {% else %}
                            - {{recipeingredient.style }}</li>
                        {% endif %}
                {% empty %}
                    <li>No ingredients</li>
                {% endfor %}
            </ul>
            <h3>Directions</h3>
            <p>{{ recipe.directions|linebreaksbr }}</p> <!--Added linebreaksbr - treats line breaks as new paragraphs -->
        </div>
    </main>
    <script type="text/javascript">
        const a = document.getElementById("multiplier");
        var old_mult = a.options[a.selectedIndex].value;

        a.addEventListener("change", multiply_ings);
        a.addEventListener("mousedown", restore_qtys);
        
        // Updates the old multiplier global variable
        function restore_qtys() {
            var b = document.getElementById("multiplier");
            old_mult = parseFloat(b.options[b.selectedIndex].value);
            console.log(old_mult);
        }

        // Scales the recipe ingredients and number of servings by the factor in the dropdown (factor = new multipler / old multiplier)
        // TODO - add rounding / data loss prevention
        function multiply_ings() {
            var mult = document.getElementById("multiplier");
            var qtys = document.getElementsByClassName("ing_qty");
            var servings = document.getElementById("servings");
            
            servings.innerHTML = parseFloat(servings.innerHTML) * (parseFloat(mult.options[mult.selectedIndex].value) / old_mult);

            for (i=0; i < qtys.length; i++) {
                qtys[i].innerHTML = parseFloat(qtys[i].innerHTML) * (parseFloat(mult.options[mult.selectedIndex].value) / old_mult);
            }

        }


    </script>
{% endblock content %}

templates/recipe_edit.html
<!-- templates/recipe_edit.html -->

{% extends 'base.html' %}

{% block content %}
    <div class="submenu">
        <a href="{% url 'recipe_new' %}">New Recipe</a>
        <span> // </span>
        <a href="{% url 'ingredients' %}">Ingredients</a>
        <span> // </span>

    </div> 
    <main>
        <h2>Edit Recipe</h2>
        <form action="" method="post">
            {% csrf_token %}
            
            <p>Name: {{ recipe_form.name }}</p>
            <p>Prep Time: {{ recipe_form.prep_time }}</p>
            <p>Cook Time: {{ recipe_form.cook_time }}</p>
            <p>Servings: {{ recipe_form.servings }}</p>
            

            <h3>Ingredients</h3>
            
            
            <table>
                <tr>
                    <th>Ingredient</th>
                    <th>Qty</th>
                    <th>Units</th>
                    <th>Style</th>
                </tr>
                {% for recipeingredient in recipeingredient_forms %}
                    <tr>
                        <td>{{ recipeingredient.ingredient }}</td>
                        <td>{{ recipeingredient.quantity }}</td>
                        <td>{{ recipeingredient.units }}</td>
                        <td>{{ recipeingredient.style }}</td>
                    </tr>
                {% endfor %}         
            </table>
            <a href="#">+ Add Ingredient</a>
            <h3>Directions</h3>
            <p>{{ recipe_form.directions }}</p>
            <input type="submit" value="Update">
        </form>
    </main>

{% endblock content %}

templates/recipe_ing_add.html
{% extends 'base.html' %}

{% block content %}
    <main>
        <h3>Edit Recipe Ingredients</h3>
        <form action="" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            
            <input type="submit" value="Update">
        </form>
    </main>

{% endblock content %}

templates/recipe_new.html
<!-- templates/recipe_new.html -->

{% extends 'base.html' %}

{% block content %}
<main>
    <h2>New Recipe</h2>
    <form action="" method="post">{% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Save">
    </form>
</main>
{% endblock content %}

templates/recipeingredient_edit.html
{% extends 'base.html' %}

{% block content %}
    <main>
        <h3>Edit Recipe Ingredients</h3>
        <form action="" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            
            <input type="submit" value="Update">
        </form>
    </main>

{% endblock content %}